# Generated by Django 2.1.7 on 2019-02-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_called',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='participation_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('SR', 'Senior'), ('JR', 'Junior')], default='FR', max_length=2),
        ),
    ]
