# Generated by Django 2.1.7 on 2019-02-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation_app', '0002_auto_20190225_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='times_called',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_in_school',
            field=models.CharField(choices=[('SR', 'Senior'), ('SO', 'Sophomore'), ('FR', 'Freshman'), ('JR', 'Junior')], default='FR', max_length=2),
        ),
    ]
