# Generated by Django 2.1.7 on 2019-03-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation_app', '0003_auto_20190225_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='present',
            field=models.CharField(choices=[('TR', 'Tardy'), ('OT', 'On-Time'), ('AB', 'Absent')], default='OT', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_in_school',
            field=models.CharField(choices=[('SO', 'Sophomore'), ('JR', 'Junior'), ('FR', 'Freshman'), ('SR', 'Senior')], default='FR', max_length=2),
        ),
    ]
