# Generated by Django 2.1.7 on 2019-03-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation_app', '0007_auto_20190310_1905'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='present',
            field=models.CharField(choices=[('OT', 'On-Time'), ('AB', 'Absent'), ('TR', 'Tardy')], default='AB', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_in_school',
            field=models.CharField(choices=[('SR', 'Senior'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('FR', 'Freshman')], default='FR', max_length=2),
        ),
    ]
