# Generated by Django 2.1.7 on 2019-03-10 19:25

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('participation_app', '0008_auto_20190310_1921'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('is_present', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='present',
            field=models.CharField(choices=[('OT', 'On-Time'), ('TR', 'Tardy'), ('AB', 'Absent')], default='AB', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_in_school',
            field=models.CharField(choices=[('SR', 'Senior'), ('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior')], default='FR', max_length=2),
        ),
    ]
