# Generated by Django 2.1.7 on 2019-03-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation_app', '0010_auto_20190310_1925'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='present',
            field=models.CharField(choices=[('OT', 'On-Time'), ('TR', 'Tardy'), ('AB', 'Absent')], default='AB', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_in_school',
            field=models.CharField(choices=[('JR', 'Junior'), ('FR', 'Freshman'), ('SO', 'Sophomore'), ('SR', 'Senior')], default='FR', max_length=2),
        ),
    ]
