# Generated by Django 2.1.7 on 2019-03-13 06:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('participation_app', '0011_auto_20190310_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('called', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='participation_points',
        ),
        migrations.RemoveField(
            model_name='student',
            name='times_called',
        ),
        migrations.AlterField(
            model_name='student',
            name='year_in_school',
            field=models.CharField(choices=[('SO', 'Sophomore'), ('FR', 'Freshman'), ('SR', 'Senior'), ('JR', 'Junior')], default='FR', max_length=2),
        ),
        migrations.AddField(
            model_name='participation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='participation_app.Student'),
        ),
    ]
