# Generated by Django 2.1.7 on 2019-03-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation_app', '0012_auto_20190313_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='times_called',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='present',
            field=models.CharField(choices=[('TR', 'Tardy'), ('OT', 'On-Time'), ('AB', 'Absent')], default='AB', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_in_school',
            field=models.CharField(choices=[('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('FR', 'Freshman')], default='FR', max_length=2),
        ),
    ]
