# Generated by Django 2.1.7 on 2019-03-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation_app', '0013_auto_20190313_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='participation_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='present',
            field=models.CharField(choices=[('OT', 'On-Time'), ('AB', 'Absent'), ('TR', 'Tardy')], default='AB', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_in_school',
            field=models.CharField(choices=[('SR', 'Senior'), ('JR', 'Junior'), ('SO', 'Sophomore'), ('FR', 'Freshman')], default='FR', max_length=2),
        ),
    ]
