# Generated by Django 2.1.7 on 2019-03-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation_app', '0014_auto_20190313_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(default='F N', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='present',
            field=models.CharField(choices=[('TR', 'Tardy'), ('AB', 'Absent'), ('OT', 'On-Time')], default='AB', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_in_school',
            field=models.CharField(choices=[('SR', 'Senior'), ('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior')], default='FR', max_length=2),
        ),
    ]
